filebeat.inputs:
  - type: log
    paths:
      - /var/log/nginx/access.log
    tail_files: true
    fields_under_root: true
    fields:
      type: nginx_access

  - type: log
    paths:
      - /var/log/nginx/error.log
    tail_files: true
    fields_under_root: true
    fields:
      type: nginx_error

  - type: log
    paths:
      - /var/log/secure
    tail_files: true
    fields_under_root: true
    fields:
      type: syslog

# output.logstash:
#   hosts: ["logstash:5044"]

output.redis:
  hosts: [ "redis" ]
  password: "changeme"
  key: 'filebeat'
