filebeat.inputs:
  - type: log
    tail_files: true
    enabled: true
    backoff: "1s"
    paths:
      - /tmp/logs/nginx_access.log
    fields:
      type: nginx
    fields_under_root: true

  - type: log
    tail_files: true
    enabled: true
    backoff: "1s"
    paths:
      - /tmp/logs/messages
    fields:
      type: syslog
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]
